name: Automação Promos Amazon

on:
  schedule:
    - cron: '*/30 * * * *' # Roda a cada 30 minutos, todos os dias
  workflow_dispatch: # Permite rodar manualmente para testar

permissions:
  contents: write # Permissão para salvar o arquivo de histórico

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar dependências
        run: pip install requests

      - name: Rodar Robô Amazon
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
          AMAZON_TAG: ${{ secrets.AMAZON_TAG }}
        run: python main.py

      - name: Salvar Histórico (posted_deals.txt)
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          touch posted_deals.txt
          git add posted_deals.txt
          git diff --quiet && git diff --staged --quiet || (git commit -m "Atualiza histórico [skip ci]" && git push)
