name: Automacao Promos Amazon

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  check-deals:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar dependencias
        run: pip install requests beautifulsoup4

      - name: Executar robo Amazon
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
          AMAZON_TAG: ${{ secrets.AMAZON_TAG }}
        run: python main.py

      - name: Salvar historico
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          touch posted_deals.txt
          git add posted_deals.txt
          git diff --quiet && git diff --staged --quiet || (git commit -m "Atualiza historico [skip ci]" && git push)
